# Site settings
author: Lorena Giddens
title: Journey Through Code
header-img: img/cyber-3728141_1920.jpg
email: lorena.giddens@outlook.com
copyright_name: Lorena Giddens
description: > # this means to ignore newlines until "baseurl:"
  & code through the journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username:  pracniscate

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
