# Site settings
title: 
header-img: img/home-bg.png
email: lorena.giddens@outlook.com
copyright_name: pracniscate
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pracniscate
learn_profile: pracniscate
email_username: lorena.giddens@outlook.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
